# User config
author: "ivanczhuang"
tagline: ""
description: "A bit of a blog"
keywords: ""
email: "iczhuang09@gmail.com"
linkedin: "https://www.linkedin.com/in/ivan-zhuang"
instagram: "https://www.instagram.com/ivanczhuang"
github: "https://github.com/hi1van"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed